tmp_dir: /tmp/installer
wait_for_start: 20
customJavaPath: false
security: PLAINTEXT__ZK_PLAIN_NO_AUTH__KAFKA_PLAINTEXT_NO_AUTH
kafka_user: kafka
kafka_group: kafka
zookeeper_user: kafka
zookeeper_group: kafka
enabled_service: true

kafka:
    distr: distrib.zip
    installdir: /pub/opt/Apache/kafka
    logdir: /pub/opt/Apache/kafka/logs
    datadir: /pub/KAFKADATA
    cleanLog: false
    cleanData: false

zookeeper:
    distr: distrib.zip
    installdir: /pub/opt/Apache/kafka
    logdir: /pub/opt/Apache/kafka/logs
    datadir: /pub/zookeeper
    cleanLog: false
    cleanData: false

crxsr:
  distr: distrib.zip
  installdir: /pub/opt/Apache/kafka
  cleanLog: false
  prop_var:
    "server_port": 8081

crxui:
    distr: distrib.zip
    installdir: /pub/opt/Apache/kafka
    cleanLog: false
    cleanData: false
    server.port: 9090
